version: '3.3'

networks:
 default:
    external:
      name: mynetwork

services:

  mariadev:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=mariadev
      - MARIADB_DATABASE=mariadev
    volumes:
      - mariadb_data:/bitnami

volumes:
  mariadb_data:
    driver: local
