version: '3.3'

networks:
 default:
    external:
      name: mynetwork

services:

  mariadev:
    image: 'bitnami/mariadb:latest'
    user: root
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_HOST=mariadev
      - MARIADB_DATABASE=mariadev
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
    ports:
      - 3308:3306
    volumes:
      - ./devdb:/bitnami
