version: '3.3'

networks:
  default:
    external:
      name: myNet

services:

  mariadb_wp:
    image: 'bitnami/mariadb:latest'
    restart: always
    user: root
    ports:
      - '3308'
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=wpadmin
      - MARIADB_PORT_NUMBER=3308
      - MARIADB_DATABASE=mariadb_wp
    volumes:
      - ./wpDb:/bitnami

  wordpress:
    image: 'bitnami/wordpress:latest'
    restart: always
    user: root
    ports:
      - '81:80'
      - '443:443'
    links:
      - mariadb_wp:mariadb
    volumes:
      - './wp:/bitnami'
    depends_on:
      - mariadb_wp
    environment:
      - MARIADB_HOST=mariadb_wp
      - MARIADB_PORT_NUMBER=3308
      - WORDPRESS_DATABASE_PASSWORD=wpadmin
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_NAME=mariadb_wp
      - WORDPRESS_PASSWORD=wpadmin
      - WORDPRESS_USERNAME=wpadmin
